### PR TITLE
Build system update + bugfixing

### PR DESCRIPTION
**Pull request by lmroz**
- Updated build scripts (plugin with old ones no longer builds for me)
- Ran gofmt on each file

- Changed config policy from required field with default value to optional which is manually set if missing.
Without this change plugin has correct value from global config in `GetMetricTypes`, but in `CollectMetrics` the field is overwritten with default one.

### CODE REVIEW

**Comment by ssenthil416** [comment]
OK

**Review by ssenthil416 — APPROVED** [review]
ok

**Comment by lmroz** [comment]
@ssenthil416 You gave approval for this PR, but you have closed it without merging. I'm not sure if it's a missclick or you want it reworked (e.g. more atomic commits).

**Comment by ssenthil416** [comment]
Yes I also noticed it. Can you please share the merge link

**Comment by ssenthil416** [comment]
Yes I also noticed it. Can you please share the merge link

**Comment by lmroz** [comment]
You can reopen this pull request at the very bottom of the page, just below comment box. Then just above this box frame with merge button should pop up.

**Comment by ssenthil416** [comment]
Done. Thanks

**Pull request merged**
